"""Tests for app/image.py.

Two testing strategies, mirroring the pattern used elsewhere in this
project (mock the heavy/nondeterministic boundary, exercise the
deterministic logic directly):

- A handful of tests run the REAL rembg pipeline end-to-end against the
  5 deliberately-bad fixtures in tests/fixtures/bad_photos/ (generated by
  scripts/generate_bad_test_images.py), using the lightweight u2netp
  model (see conftest.py) for speed. These catch real integration bugs —
  in fact, they're exactly how the white-balance/cyan-background bug
  documented in _gray_world_white_balance's docstring was found.
- Most tests mock app.image._remove_background to return a controlled
  RGBA cutout, so cropping/padding/white-balance/output-spec logic can be
  tested precisely and fast, without depending on what a real ML model
  happens to segment.
"""

from pathlib import Path

import cv2
import numpy as np
import pytest
from PIL import Image

import app.image as image_module
from app.image import clean_product_image, thumbnail_path_for

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures" / "bad_photos"


# ---------------------------------------------------------------------------
# helpers for the mocked-background-removal tests
# ---------------------------------------------------------------------------


def _make_source_photo(path: Path, size: int = 400, bg=(240, 240, 240), fg=(150, 60, 40)):
    """A simple sharp product-on-background photo, saved to `path`."""
    from PIL import ImageDraw

    img = Image.new("RGB", (size, size), bg)
    draw = ImageDraw.Draw(img)
    margin = size // 4
    draw.ellipse([margin, margin, size - margin, size - margin], fill=fg)
    img.save(path, quality=95)
    return path


def _make_rgba_cutout(size: int = 400, fg=(150, 60, 40), circle_frac: float = 0.5) -> Image.Image:
    """A synthetic RGBA "background-removed" result: an opaque circle on
    a transparent field, standing in for whatever rembg would produce.
    """
    rgba = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    from PIL import ImageDraw

    draw = ImageDraw.Draw(rgba)
    r = size * circle_frac / 2
    cx, cy = size // 2, size // 2
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(*fg, 255))
    return rgba


@pytest.fixture
def mock_background_removal(monkeypatch):
    """Returns a setter: call it with an RGBA image to control exactly
    what `clean_product_image` sees from background removal.
    """

    def _set(rgba: Image.Image):
        monkeypatch.setattr(image_module, "_remove_background", lambda pil_rgb: rgba)

    return _set


def _corner_pixel(clean_path: str) -> tuple[int, int, int]:
    img = Image.open(clean_path).convert("RGB")
    return img.getpixel((2, 2))


# ---------------------------------------------------------------------------
# Blur check (step 1) — real pipeline, using the fixtures
# ---------------------------------------------------------------------------


def test_blurry_image_stops_pipeline_with_retake_warning(tmp_path):
    result = clean_product_image(FIXTURES_DIR / "blurry.jpg", output_dir=tmp_path)
    assert result == {"clean_path": None, "alpha_path": None, "warnings": ["retake"]}
    assert list(tmp_path.iterdir()) == []  # nothing written


def test_dark_but_sharp_image_is_not_falsely_flagged_as_blurry(tmp_path):
    # Regression test: naive variance-of-Laplacian on the raw (unequalized)
    # image would flag this as blurry purely because it's dark, not
    # because it's actually out of focus. See _blur_score's docstring.
    result = clean_product_image(FIXTURES_DIR / "dark.jpg", output_dir=tmp_path)
    assert "retake" not in result["warnings"]
    assert result["clean_path"] is not None


def test_blur_score_ranks_blurry_below_sharp_images():
    scores = {}
    for name in ("blurry", "dark", "cluttered", "off_white", "tight_crop"):
        bgr = cv2.imread(str(FIXTURES_DIR / f"{name}.jpg"))
        gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
        scores[name] = image_module._blur_score(gray)

    assert scores["blurry"] < image_module.BLUR_THRESHOLD
    for name in ("dark", "cluttered", "off_white", "tight_crop"):
        assert scores[name] > scores["blurry"]
        assert scores[name] >= image_module.BLUR_THRESHOLD


# ---------------------------------------------------------------------------
# Background is always pure white (steps 2-3), regardless of input —
# real pipeline, using the fixtures
# ---------------------------------------------------------------------------


def test_off_white_input_background_becomes_pure_white(tmp_path):
    result = clean_product_image(FIXTURES_DIR / "off_white.jpg", output_dir=tmp_path)
    assert result["warnings"] == []
    assert _corner_pixel(result["clean_path"]) == (255, 255, 255)


def test_cluttered_background_is_removed_and_becomes_pure_white(tmp_path):
    result = clean_product_image(FIXTURES_DIR / "cluttered.jpg", output_dir=tmp_path)
    assert _corner_pixel(result["clean_path"]) == (255, 255, 255)


def test_tight_crop_gets_white_padding_even_with_no_source_margin(tmp_path):
    result = clean_product_image(FIXTURES_DIR / "tight_crop.jpg", output_dir=tmp_path)
    # The source image has virtually no margin around the product; the
    # padded corner must still come out pure white (extended canvas, not
    # a slice of the product itself).
    assert _corner_pixel(result["clean_path"]) == (255, 255, 255)


# ---------------------------------------------------------------------------
# White balance must never tint a background that's already pure white —
# this is the exact regression the module's docstring documents
# ---------------------------------------------------------------------------


def test_white_balance_does_not_tint_white_background_with_saturated_product(
    tmp_path, mock_background_removal
):
    # A strongly saturated product filling most of the frame — this is
    # exactly the scenario that broke naive (unmasked) gray-world: the
    # product's own colour dominated the frame average so badly that the
    # correction shifted the pure-white padding to cyan.
    rgba = _make_rgba_cutout(size=400, fg=(160, 70, 40), circle_frac=0.85)
    mock_background_removal(rgba)

    source = _make_source_photo(tmp_path / "src.jpg", size=400)
    result = clean_product_image(source, output_dir=tmp_path)

    corner = _corner_pixel(result["clean_path"])
    # Allow a couple of levels of JPEG-compression/resize rounding, but
    # it must be white, not visibly tinted.
    assert all(c >= 250 for c in corner), f"background corner {corner} is not white"


def test_gray_world_white_balance_mask_changes_the_estimate():
    # The mask controls which pixels the gray-world *estimate* is
    # measured from (see the function's docstring) — it does not, by
    # itself, guarantee the background stays white; that guarantee comes
    # from clean_product_image re-compositing onto white afterwards
    # (see test_white_balance_does_not_tint_white_background_with_
    # saturated_product, which tests exactly that end-to-end). Here we
    # just confirm the mask parameter actually has an effect: measuring
    # from only the red region vs. the whole (half-red, half-white) frame
    # must produce different corrections.
    bgr = np.full((100, 100, 3), (40, 60, 200), dtype=np.uint8)  # BGR: strong red
    bgr[:, 50:] = (255, 255, 255)  # right half is neutral

    fg_mask = np.zeros((100, 100), dtype=bool)
    fg_mask[:, :50] = True

    masked = image_module._gray_world_white_balance(bgr, fg_mask=fg_mask)
    unmasked = image_module._gray_world_white_balance(bgr, fg_mask=None)

    assert not np.array_equal(masked, unmasked)


def test_gray_world_white_balance_falls_back_to_whole_frame_when_mask_is_all_false():
    bgr = np.full((20, 20, 3), (100, 120, 140), dtype=np.uint8)
    empty_mask = np.zeros((20, 20), dtype=bool)

    # Must not crash (e.g. divide-by-zero on an empty mean) — falls back
    # to whole-frame statistics per the function's documented behaviour.
    result = image_module._gray_world_white_balance(bgr, fg_mask=empty_mask)
    assert result.shape == bgr.shape


# ---------------------------------------------------------------------------
# Output spec: 2000x2000 JPEG q90 clean, 600x600 thumbnail, square, RGBA alpha
# ---------------------------------------------------------------------------


def test_output_dimensions_and_formats(tmp_path, mock_background_removal):
    mock_background_removal(_make_rgba_cutout())
    source = _make_source_photo(tmp_path / "src.jpg")

    result = clean_product_image(source, output_dir=tmp_path)

    clean = Image.open(result["clean_path"])
    assert clean.size == (image_module.FINAL_SIZE, image_module.FINAL_SIZE)
    assert clean.format == "JPEG"

    thumb = Image.open(thumbnail_path_for(result["clean_path"]))
    assert thumb.size == (image_module.THUMB_SIZE, image_module.THUMB_SIZE)

    alpha = Image.open(result["alpha_path"])
    assert alpha.mode == "RGBA"
    assert alpha.width == alpha.height  # square, same crop as clean_path


def test_clean_jpeg_uses_configured_quality(tmp_path, mock_background_removal, monkeypatch):
    mock_background_removal(_make_rgba_cutout())
    source = _make_source_photo(tmp_path / "src.jpg")

    result_default = clean_product_image(source, output_dir=tmp_path / "q_default")
    size_default = Path(result_default["clean_path"]).stat().st_size

    monkeypatch.setattr(image_module, "JPEG_QUALITY", 30)
    result_low_q = clean_product_image(source, output_dir=tmp_path / "q_low")
    size_low_q = Path(result_low_q["clean_path"]).stat().st_size

    assert size_low_q < size_default  # lower quality -> smaller file


def test_return_dict_has_exactly_the_specified_keys(tmp_path, mock_background_removal):
    mock_background_removal(_make_rgba_cutout())
    source = _make_source_photo(tmp_path / "src.jpg")

    result = clean_product_image(source, output_dir=tmp_path)
    assert set(result.keys()) == {"clean_path", "alpha_path", "warnings"}


def test_thumbnail_path_for_convention():
    assert thumbnail_path_for("/x/y/foo_clean.jpg") == Path("/x/y/foo_clean_thumb.jpg")


# ---------------------------------------------------------------------------
# Cropping math: 8% padding, square output, centered on the alpha bbox
# ---------------------------------------------------------------------------


def test_output_is_square_for_non_square_source(tmp_path, mock_background_removal):
    # A wide RGBA cutout on a wide canvas — the crop/pad logic must still
    # square it up.
    rgba = Image.new("RGBA", (600, 300), (0, 0, 0, 0))
    from PIL import ImageDraw

    ImageDraw.Draw(rgba).ellipse([200, 75, 400, 225], fill=(150, 60, 40, 255))
    mock_background_removal(rgba)

    source = _make_source_photo(tmp_path / "src.jpg", size=400)
    result = clean_product_image(source, output_dir=tmp_path)

    alpha = Image.open(result["alpha_path"])
    assert alpha.width == alpha.height


def test_padding_is_approximately_8_percent_of_content_size(tmp_path, mock_background_removal):
    rgba = Image.new("RGBA", (400, 400), (0, 0, 0, 0))
    from PIL import ImageDraw

    ImageDraw.Draw(rgba).rectangle([100, 100, 300, 300], fill=(150, 60, 40, 255))
    # PIL draws rectangle() inclusive of the far corner, so measure the
    # actual bbox rather than assuming it matches the drawn coordinates.
    bbox = rgba.split()[-1].getbbox()
    content_size = max(bbox[2] - bbox[0], bbox[3] - bbox[1])
    mock_background_removal(rgba)

    source = _make_source_photo(tmp_path / "src.jpg", size=400)
    result = clean_product_image(source, output_dir=tmp_path)

    alpha = Image.open(result["alpha_path"])
    expected_size = round(content_size * (1 + 2 * image_module.PADDING_FRACTION))
    assert alpha.width == expected_size


def test_no_subject_detected_falls_back_to_full_frame_with_warning(tmp_path, mock_background_removal):
    fully_transparent = Image.new("RGBA", (300, 300), (0, 0, 0, 0))
    mock_background_removal(fully_transparent)

    source = _make_source_photo(tmp_path / "src.jpg", size=300)
    result = clean_product_image(source, output_dir=tmp_path)

    assert "no_subject_detected" in result["warnings"]
    assert result["clean_path"] is not None  # still produces output, doesn't crash


# ---------------------------------------------------------------------------
# Model selectability (env var) — the licensing-critical requirement
# ---------------------------------------------------------------------------


def test_rembg_model_is_configurable_via_env_var(monkeypatch):
    monkeypatch.setattr(image_module, "REMBG_MODEL", "some-other-model")
    monkeypatch.setattr(image_module, "_session", None)

    captured = {}

    def fake_new_session(model_name):
        captured["model_name"] = model_name
        return "fake-session"

    monkeypatch.setattr("rembg.new_session", fake_new_session)

    session = image_module._get_rembg_session()
    assert session == "fake-session"
    assert captured["model_name"] == "some-other-model"


def test_default_rembg_model_is_not_rembgs_own_default():
    # rembg's own new_session() default is "bria-rmbg" (confirmed by
    # inspecting its signature — see app/image.py's module docstring),
    # which requires a paid commercial licence. This module must never
    # rely on that default.
    #
    # Checked against the literal fallback in the source (not
    # image_module.REMBG_MODEL, which tests/conftest.py deliberately
    # overrides to the lightweight u2netp for test speed) — this test is
    # about what a deployment with no CRAFTLY_REMBG_MODEL set would get.
    import inspect

    from rembg import new_session

    rembg_own_default = inspect.signature(new_session).parameters["model_name"].default

    source = Path(image_module.__file__).read_text()
    assert 'os.environ.get("CRAFTLY_REMBG_MODEL", "u2net")' in source
    assert rembg_own_default != "u2net"


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_unreadable_file_raises_value_error(tmp_path):
    bad_file = tmp_path / "not_an_image.jpg"
    bad_file.write_bytes(b"not actually image data")

    with pytest.raises(ValueError):
        clean_product_image(bad_file, output_dir=tmp_path)
