"""The wire types this service speaks.

Same duplication-with-a-parity-test discipline C1 uses, and for the same
reason: three packages in this repo are called ``app`` and none of them is
installable, so ``from app.schema import Listing`` inside ``platform/``
would resolve to *this* package. The mirror is checked, not trusted —
``tests/test_schema_parity.py`` loads A2's ``capture/app/schema.py`` and
C1's ``market/app/contracts.py`` from disk and fails if any of the three
copies drift apart.

**If that test goes red, do not edit this file to make it pass.** A schema
change is a team-wide announcement. A red parity test means the
announcement happened somewhere B2 did not hear it.

What is *not* here: ``PriceQuote`` and ``SplitPlan``. Those are B1's
output. B2 stores them verbatim on an order line when C1 hands them over —
this service never computes a price, and a platform that quietly recomputes
one is a platform that can disagree with the number the buyer was shown.

The null rule holds throughout: a missing number is ``None``, never ``0``.
``material_cost_inr`` and ``hours_worked`` feed a minimum-wage floor, and
``0`` there means "she said it cost nothing", which is a different fact
from "nobody has asked her yet".
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Mirror of the shared Listing contract (source of truth: capture/app/schema.py)
# ---------------------------------------------------------------------------


class Listing(BaseModel):
    listing_id: str
    artisan_id: str

    source_language: str | None = None
    transcript_raw: str | None = None

    title_en: str | None = None
    title_hi: str | None = None
    description_en: str | None = None
    description_hi: str | None = None

    summary_spoken: str | None = None

    category: str | None = None
    craft_type: str | None = None
    material: str | None = None
    colours: list[str] | None = None
    dimensions: str | None = None

    material_cost_inr: int | None = None
    hours_worked: float | None = None

    confidence: dict[str, float] = Field(default_factory=dict)
    needs_confirmation: list[str] = Field(default_factory=list)

    image_original_url: str | None = None
    image_clean_url: str | None = None

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Records B2 owns outright
# ---------------------------------------------------------------------------


class Channel(str, Enum):
    OWN_STORE = "own_store"
    B2B = "b2b"
    MELA_QR = "mela_qr"
    AMAZON = "amazon"
    FLIPKART = "flipkart"
    EBAY = "ebay"


class Artisan(BaseModel):
    artisan_id: str
    name: str
    village: str | None = None
    district: str | None = None
    state: str | None = None
    craft: str | None = None
    cluster_id: str | None = None
    years_experience: int | None = None
    languages: list[str] = Field(default_factory=list)
    photo_url: str | None = None
    story: str | None = None


class Inventory(BaseModel):
    listing_id: str
    in_stock: int = 0
    made_to_order: bool = True
    lead_time_days: int | None = None
    monthly_capacity: int | None = None
    cluster_capacity: int | None = None


class PassportStep(BaseModel):
    label: str
    detail: str | None = None
    at: datetime | None = None


class Passport(BaseModel):
    listing_id: str
    verification_code: str
    artisan: Artisan
    craft_type: str | None = None
    material: str | None = None
    hours_worked: float | None = None
    material_cost_inr: int | None = None
    made_at: str | None = None
    issued_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    making_clip_url: str | None = None
    image_url: str | None = None
    qr_url: str | None = None
    chain: list[PassportStep] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Orders — produced by C1, persisted and settled here
# ---------------------------------------------------------------------------


class OrderKind(str, Enum):
    RETAIL = "retail"
    BULK = "bulk"


class OrderStatus(str, Enum):
    PLACED = "placed"
    ACCEPTED = "accepted"
    IN_PRODUCTION = "in_production"
    DISPATCHED = "dispatched"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class Buyer(BaseModel):
    name: str
    phone: str
    email: str | None = None
    organisation: str | None = None
    address: str | None = None
    city: str | None = None
    state: str | None = None
    pincode: str | None = None
    country: str = "IN"


class Allocation(BaseModel):
    """One artisan's share of a split bulk line. B1 computes it; B2 pays it."""

    artisan_id: str
    artisan_name: str
    village: str | None = None
    quantity: int
    lead_time_days: int | None = None
    take_home_inr: int | None = None


class SplitPlan(BaseModel):
    listing_id: str
    quantity_requested: int
    quantity_allocated: int
    allocations: list[Allocation] = Field(default_factory=list)
    lead_time_days: int | None = None
    feasible: bool = True
    shortfall: int = 0
    notes: list[str] = Field(default_factory=list)


class OrderLine(BaseModel):
    listing_id: str
    title: str
    quantity: int
    unit_price_inr: int
    channel: Channel = Channel.OWN_STORE
    artisan_take_home_inr: int | None = None
    split: SplitPlan | None = None

    @property
    def subtotal_inr(self) -> int:
        return self.unit_price_inr * self.quantity


class Order(BaseModel):
    order_id: str
    kind: OrderKind = OrderKind.RETAIL
    status: OrderStatus = OrderStatus.PLACED
    buyer: Buyer
    lines: list[OrderLine] = Field(default_factory=list)
    channel: Channel = Channel.OWN_STORE
    deadline: datetime | None = None
    notes: str | None = None
    source: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_inr(self) -> int:
        return sum(line.subtotal_inr for line in self.lines)

    @property
    def artisan_total_inr(self) -> int:
        return sum((line.artisan_take_home_inr or 0) * line.quantity for line in self.lines)

    @property
    def unit_count(self) -> int:
        return sum(line.quantity for line in self.lines)


# ---------------------------------------------------------------------------
# The catalogue join C1 reads
# ---------------------------------------------------------------------------


class CatalogEntry(BaseModel):
    """A listing plus everything a shelf needs: who made it, and how much exists.

    This is the shape ``GET /catalog/entries`` returns, and it is exactly
    what ``market/app/adapters/http_platform.py:_entry_from_json`` parses.
    """

    listing: Listing
    artisan: Artisan
    inventory: Inventory
    published: bool = True
    channels: list[Channel] = Field(default_factory=lambda: [Channel.OWN_STORE])
